---
title: "Report on Snickers and Coca-Cola Prices"
author: "Lagos Team"
date: "1 November 2021"
output:
  html_document:
    df_print: paged
    toc: yes
  pdf_document:
    toc: yes
---

```{r echo=FALSE, include=FALSE}
#knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
# Set graph size
#knitr::opts_chunk$set(echo = FALSE, out.width = "50%" )#fig.asp = 0.5, fig.width = 7, out.width = "90%" )

# Loading packages with pacman
if (!require("pacman")) {
  install.packages("pacman")
}

pacman::p_load(tidyverse, modelsummary, viridis,
               kableExtra)

# Import data
df <- read.csv( 'https://raw.githubusercontent.com/nszoni/lagos-team/main/coding-1/data/Data_DA1_HW1_Lagos.csv' )

```


```{r echo=FALSE, include=FALSE}

### Data cleaning


df_clean <- df %>% 
  mutate(google_rating = as.numeric(ifelse(google_rating!='N/A', substr(google_rating,1,3), NA)), # 1. Correct ratings and NAs
         number_of_reviews = as.numeric(ifelse(number_of_reviews=='N/A', NA, number_of_reviews)), # 2. Correct number of reviews NA
         shop_type_group = as.factor(ifelse(shop_type %in% c('Grocery', 'Gas station', "Supermarket", "Other"), "Big shop", "Small shop")), # 3. Create group for shop size
         is_discounted = as.factor(ifelse(is_discounted=='Y', 1, 0)), # 4. Replace booelan flags
         has_website = as.factor(ifelse(has_website=='Y', 1, 0)),
         longitude = as.numeric(longitude), # 5. Data casting
         latitude = as.numeric(latitude),
         google_rating = as.numeric(google_rating),
         number_of_reviews = as.integer(number_of_reviews),
         collection_date = as.POSIXct(collection_date),
         district = as.factor(district), 
         item_name = ifelse(item_name == 'Coca Cola, 0.5l plastic bottle', 'Coke 0.5l', 'Snickers 50g')) #5. Shortening item names

```

## Introduction
HERE COMES THE MOTIVATION WHY THIS IS A MEANINGFUL PROJECT AND WHAT IS THE MAIN GOAL!

## Data
HERE COMES A DETAILLED EXPLANATION ABOUT WHERE THE DATA COMES FROM AND IF IT IS REPRESENTATIVE OR NOT.


```{r, echo=FALSE}

# Summary table
P95 <- function(x){quantile(x,0.95,na.rm=T)}
P05 <- function(x){quantile(x,0.05,na.rm=T)}


# Ali do some table formatting with kableExtra package pls

datasummary(  (`District` = as.factor(district) ) * (`Product` = as.factor(item_name)) * (`Price` = price_huf ) ~ 
             NUnique + PercentMissing + Mean + SD + Min + Max +  P05 + Median + P95 + Histogram, 
             data = df,
             title = 'Descriptive statistics of prices by district',
             notes = 'Intuitively the mean of both products are slightly higher in the inner 13th district. Also there is less variation in price of Snicker bars and more variation in the price of Coke. Those who are living in the inner city have to pay a larger entry price for Coke. The distribution of prices in teh inner district is shofted a bit considering the percentiles' )

# by shop size     
# datasummary(  (`Shop type` = as.factor(shop_type_group) ) * (`District` = as.factor(district) ) * (`Product` = as.factor(item_name)) * (`Price` = price_huf ) ~ 
#              NUnique + PercentMissing + Mean + SD + Min + Max +  P05 + Median + P95, 
#              data = df,
#              title = 'Descriptive statistics of prices by district and shop size',
#              notes = 'Add some notes' )

```

# Viz

```{r echo = F}
df_11 <- df %>% 
  filter(item_name == 'Snickers bar (50g)' & district == 10) 

df_12 <- df %>% 
  filter(item_name == 'Snickers bar (50g)' & district == 13) 

df_21 <- df %>% 
  filter(item_name == 'Coca Cola, 0.5l plastic bottle' & district == 10) 

df_22 <- df %>% 
  filter(item_name == 'Coca Cola, 0.5l plastic bottle' & district == 13) 

# Histograms

# joint districtwise
# y-axis
ggplot(df) + 
  geom_histogram(aes(price_huf, y=..density.., fill=item_name), alpha=0.6, position="identity", bins = 10) +
  geom_density(aes(price_huf, y=..density.., color=item_name), alpha=5) +
  labs(x = "Price (HUF)",
       y = "Frequency",
       subtitle = "Snickers x Coke",
       title = "Price distribution (HUF)",
       caption = "lagos-team") +
  theme_classic()


ggplot(data = df_11 , aes( x = price_huf) ) +
  geom_histogram(binwidth = 20, aes( y = (..count..)/sum(..count..)), alpha =0.8) +
  labs( x = "Price" , y = 'Frequency' , title="10th district, Snickers" ) +
  scale_x_continuous(breaks = seq(0, 500, by = 50)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 5L)) +
  theme_bw() +
  theme(legend.position="none")

ggplot(data = df_12 , aes( x = price_huf) ) +
  geom_histogram(binwidth = 20, aes( y = (..count..)/sum(..count..)), alpha =0.8) +
  labs( x = "Price" , y = 'Frequency', title="13th district, Snickers"  ) +
  scale_x_continuous(breaks = seq(0, 500, by = 50)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 5L)) +
  theme_bw() +
  theme(legend.position="none")

ggplot(data = df_21 , aes( x = price_huf) ) +
  geom_histogram(binwidth = 20, aes( y = (..count..)/sum(..count..)), alpha =0.8) +
  labs( x = "Price" , y = 'Frequency', title="10th district, Coca-Cola"  ) +
  scale_x_continuous(breaks = seq(0, 500, by = 50)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 5L)) +
  theme_bw() +
  theme(legend.position="none")

ggplot(data = df_22 , aes( x = price_huf) ) +
  geom_histogram(binwidth = 20, aes( y = (..count..)/sum(..count..)), alpha =0.8) +
  labs( x = "Price" , y = 'Frequency' , title="13th district, Coca-Cola" ) +
  scale_x_continuous(breaks = seq(0, 500, by = 50)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 5L)) +
  theme_bw() +
  theme(legend.position="none")


```


```{r echo = F}

# Boxplots

df_1 <- df %>% 
  filter(item_name == 'Snickers bar (50g)') 

ggplot(data = df_1, aes(x = factor(district), y = price_huf)) +
  stat_boxplot(aes(group = factor(district)), geom = "errorbar", width = 0.2, color = viridis(2, begin=0.2, end=0.8), size = 0.1) +
  geom_boxplot(aes(group = factor(district)),  color = viridis(2, begin=0.2, end=0.8), fill = viridis(2, begin=0.2, end=0.8), size = 0.5, width =  0.5, alpha = 0.6) +  # , outlier.shape = NA
  # geom_jitter(aes(color = factor(district)), position=position_jitter(0.1), size = 1.5, show.legend=F) +
  labs(x = "District",y = "Price")+
  scale_y_continuous(limits = c(100,350), breaks = seq(0,350,50)) +
  scale_color_viridis(discrete = TRUE, option = "D", begin = 0.2, end=0.8)+
  theme_bw() 


df_2 <- df %>% 
  filter(item_name == 'Coca Cola, 0.5l plastic bottle') 

ggplot(data = df_2, aes(x = factor(district), y = price_huf)) +
  stat_boxplot(aes(group = factor(district)), geom = "errorbar", width = 0.2, color = viridis(2, begin=0.2, end=0.8), size = 0.1) +
  geom_boxplot(aes(group = factor(district)),  color = viridis(2, begin=0.2, end=0.8), fill = viridis(2, begin=0.2, end=0.8), size = 0.5, width =  0.5, alpha = 0.6) +  # , outlier.shape = NA
  # geom_jitter(aes(color = factor(district)), position=position_jitter(0.1), size = 1.5, show.legend=F) +
  labs(x = "District",y = "Price")+
  scale_y_continuous(limits = c(100,500), breaks = seq(0,500,50)) +
  scale_color_viridis(discrete = TRUE, option = "D", begin = 0.2, end=0.8)+
  theme_bw() 

```


# Price and distance ??
```{r}

# Bin scatter (with jitter) by distance groups??

```



```{r echo = F}

# Scatterplots 

df_1 <- df %>% 
  filter(item_name == 'Snickers bar (50g)') 

#bin scatter
ggplot(data = df_1, aes(x = distance_from_city_centre_km, y = price_huf, color = factor(district))) +
  geom_point( size = 3,  shape = 16, alpha = 0.9,  na.rm = TRUE) +
  geom_smooth(method='lm') +
  scale_colour_viridis_d( begin = 0.2, end = 0.8) +
  theme_bw()


df_2 <- df %>% 
  filter(item_name == 'Coca Cola, 0.5l plastic bottle') 

ggplot(data = df_2, aes(x = distance_from_city_centre_km, y = price_huf, color = factor(district))) +
  geom_point( size = 3,  shape = 16, alpha = 0.9, show.legend=FALSE, na.rm = TRUE) +
  scale_colour_viridis_d( begin = 0.2, end = 0.8) +
  theme_bw()


```


# T-test by district
```{r}

# 2 sample t-test

# Snickers
t.test(price_huf ~ district, data = df_1) # cannot reject H0

# Cola
t.test(price_huf ~ district, data = df_2) # cannot reject H0

# Do the same by shop size as well



```




